# a weird way of telling Travis to use the fast container-based test runner instead of the slow VM-based runner.
sudo: false
language: go
go:
- '1.11.x'
git:
  depth: 1
script:
- make
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
before_deploy:
- make VERSION=${TRAVIS_TAG} release -j2
deploy:
  provider: releases
  api_key:
    secure: Vs/r1ikCiRTT+aH4nF61EUZYl8knh30IOh+fMwzgHQ0cOXy/aUwfNXnmFN8eKz73C/IUJQowZHyYZlpeps3FAELs/70MTi3DC84/VTkB1IGVay4yUKHTheitNP+CH++BAXnmgXQIowd3CuW/Dosd2CUu0AVDJUD7aNPvHWIbim4hGGB8HQ68U5CUlIOlzeo5trMomyRW991SKdHXcEQjGnFIov8AloYGgjseybXtQhH+CNhSlKvz6JZ3gPGh2B/z6Uxxc0YcFxYj6gaiAB2r+j9cKeiHGcFp/fgwxSBWaKQ8MGVx+5QX4Ngamb3W084c8P7bFTxMrMJ50v8CsLS2vCJ7vfjTS9eSNL0kgjzFrPYpZn4jnraXRcPoEEWAKDkIget6PjyIUokPbeDIocy0tU82tUti7PTiabKEzyLM5lFU9ifIe9Mr6Z1+zkvmaZwtxfUwNI8c+E4+6k8zz8B1VLfAc2AhCR15ViKloenkNHoTUNhkKfwgV1dx1NDErMfiZhw0T/EzPIpbUi0Fuzv6rIFsDOeij48IiqKRud/MysdsLgrZouiazS47/aWgiVJOl7Vi5Qqtt4iRodRqlquTVQHkEff67dTB7+CLG6tKMt0odhTBW1HTREk8pnMfWuR/wxPDXiQDUqSsKqxyl7C0t2qY75GA4sJk2VM/bdQ2mdQ=
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: asaf/notif

